data_config:
    golden: 
        node_path: /app/LRG/chunking/golden/nodes.json
      
retriever_config:
    no-retriever:
       retriever: None
      
augmenter_config:
    no-ref:
        reference: False #Default
      
llm_config:
    typhoon-v2-70b:
        model: typhoon-v2-70b-instruct-private
        temperature: 0.5
        max_tokens: 8192
        base_url: https://api.opentyphoon.ai/v1
        api_key: sk-I3DUMsy2u9BcDYmlidlWN8sy1U2OdBFFBakyD2yoV4FQeK2q
      
output_path: /app/LRG/results/e2e/v0.1/main_table
batch_size: 50
          